import Link from "next/link";

const C = {
  bg: "#070711",
  cardBg: "#12122a",
  border: "rgba(99,102,241,0.12)",
  accent: "#818cf8",
  text: "#e2e8f0",
  textDim: "#64748b",
  textBright: "#f1f5f9",
};

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: C.bg, color: C.text, fontFamily: "system-ui,-apple-system,sans-serif" }}>
      <nav style={{ borderBottom: `1px solid ${C.border}`, padding: "18px 24px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Link href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
          <div style={{ width: 32, height: 32, borderRadius: 9, background: "linear-gradient(135deg,#6366f1,#a855f7)", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 800, color: "#fff", fontSize: 11 }}>SK</div>
          <span style={{ fontSize: 18, fontWeight: 700, color: C.textBright, letterSpacing: -0.4 }}>Skripr</span>
        </Link>
        <Link href="/" style={{ fontSize: 13, color: C.textDim, textDecoration: "none" }}>← Back</Link>
      </nav>

      <div style={{ maxWidth: 760, margin: "0 auto", padding: "60px 24px 100px" }}>
        <h1 style={{ fontSize: 36, fontWeight: 800, color: C.textBright, letterSpacing: -0.5, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: C.textDim, marginBottom: 48 }}>Last updated: May 29, 2026</p>

        {[
          {
            title: "1. Acceptance of Terms",
            body: "By accessing or using Skripr ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance.",
          },
          {
            title: "2. Description of Service",
            body: "Skripr is an AI-powered YouTube script generation platform. We provide tools to generate, edit, and manage video scripts using artificial intelligence. The Service is provided on a subscription basis with usage limits per plan.",
          },
          {
            title: "3. User Accounts",
            body: "You must create an account to use the Service. You are responsible for maintaining the security of your account credentials and for all activity under your account. You must be at least 18 years old to use the Service. You may not share your account with others.",
          },
          {
            title: "4. Subscriptions and Billing",
            body: "Paid plans are billed monthly in advance. You can cancel at any time from your account settings. Cancellation takes effect at the end of the current billing period — you retain access until then. No refunds are provided for partial billing periods. We reserve the right to change pricing with 30 days notice.",
          },
          {
            title: "5. AI-Generated Content",
            body: "Scripts generated by Skripr are created using AI and are provided as-is. You own the output generated for your account. We do not claim ownership of content you generate. You are solely responsible for reviewing, editing, and ensuring the accuracy and appropriateness of generated content before publication.",
          },
          {
            title: "6. Acceptable Use",
            body: "You agree not to use the Service to generate content that is illegal, harmful, defamatory, or infringes on third-party rights. You may not attempt to reverse-engineer, scrape, or abuse the Service. Violation of these terms may result in immediate account termination without refund.",
          },
          {
            title: "7. Usage Limits",
            body: "Each subscription plan includes a monthly limit on script generations and other features as described on our pricing page. Usage resets on the first day of each calendar month. Unused credits do not roll over. Deleting scripts does not restore generation credits.",
          },
          {
            title: "8. Intellectual Property",
            body: "The Skripr platform, including its design, code, and underlying technology, is owned by Skripr and protected by intellectual property laws. You may not copy, modify, or distribute any part of the platform without written permission.",
          },
          {
            title: "9. Limitation of Liability",
            body: "Skripr is provided "as is" without warranties of any kind. To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid in the 3 months preceding the claim.",
          },
          {
            title: "10. Termination",
            body: "We may suspend or terminate your account at any time for violations of these terms. You may terminate your account at any time by cancelling your subscription and deleting your account. Upon termination, your data may be deleted in accordance with our Privacy Policy.",
          },
          {
            title: "11. Contact",
            body: "For questions about these Terms, contact us at hello@skripr.com.",
          },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 32 }}>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: C.textBright, marginBottom: 10 }}>{section.title}</h2>
            <p style={{ fontSize: 15, color: C.text, lineHeight: 1.8, margin: 0 }}>{section.body}</p>
          </div>
        ))}
      </div>

      <footer style={{ borderTop: `1px solid ${C.border}`, padding: "24px", textAlign: "center" }}>
        <p style={{ fontSize: 13, color: C.textDim, margin: 0 }}>
          <Link href="/privacy" style={{ color: C.accent, textDecoration: "none", marginRight: 20 }}>Privacy Policy</Link>
          <Link href="/" style={{ color: C.textDim, textDecoration: "none" }}>skripr.com</Link>
        </p>
      </footer>
    </div>
  );
}
